/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejerciciosjava.stream;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collector;
import java.util.stream.Collectors;

public class StreamMain {
    static List<Curso> cursos;

    static{
        cursos = new ArrayList<>();
        cursos.add(new Curso("Cursos profesional de Java", 6.5f, 50, 200));
        cursos.add(new Curso("Cursos profesional de Python", 8.5f, 60, 800));
        cursos.add(new Curso("Cursos profesional de DB", 4.5f, 70, 700));
        cursos.add(new Curso("Cursos profesional de Android", 7.5f, 10, 400));
        cursos.add(new Curso("Cursos profesional de Escritura", 1.5f, 10, 300));
    }

    public static void main(String[] args) {
        //Obtener la cantidad de cursos con una duración mayor a 5 horas.
        long numCursos5 = cursos.stream().filter(curso->curso.getDuracion()>5).count();
        //long numCursos5bis = cursos.stream().filter(curso::getDuracion(5,">")).count();
        System.out.println("[1] Cantidad de cursos con una duración mayor a 5 horas: "+numCursos5);

        //Obtener la cantidad de cursos con una duración menor a 2 horas.

        //Listar el título de todos aquellos cursos con una cantidad de vídeos mayor a 50.
        System.out.println("[2] Listar el título de todos aquellos cursos con una cantidad de vídeos mayor a 50");
        cursos.stream().filter(curso->curso.getVideos()>50).map(curso->curso.getTitulo()).forEach(System.out::println);

        //Mostrar en consola el título de los 3 cursos con mayor duración.
        System.out.println("[3] Mostrar en consola el título de los 3 cursos con mayor duracion");

        //Mostrar en consola la duración total de todos los cursos.
        double duracionTotal = cursos.stream().mapToDouble(c->c.getDuracion()).sum();
        System.out.println("[4] Mostrar en consola la duración total de todos los cursos: "+duracionTotal);
        
        //Mostrar en consola todos aquellos libros que superen el promedio en cuanto a duración se refiere.
        //Mostrar en consola la duración de todos aquellos cursos que tengan una cantidad de alumnos inscritos menor a 500.
        System.out.println("[6] Mostrar en consola la duración de todos aquellos cursos que tengan una cantidad de alumnos inscritos menor a 500");
        cursos.stream().filter(c->c.getAlumnos()<500).map(c->c.getDuracion()).collect(Collectors.toList()).forEach(System.out::println);
        //Obtener el curso con mayor duración.
        System.out.println("[7] Obtener el curso con mayor duracion");
        //cursos.stream().fmap(c->c.getDuracion())

        //Crear una lista de Strings con todos los titulos de los cursos.
        System.out.println("[8] Crear una lista de Strings con todos los titulos de los cursos");
        List<String> lCursos = cursos.stream().map(c->c.getTitulo()).collect(Collectors.toList());
        lCursos.stream().forEach(System.out::println);
    }
}
